### ISSUE TITLE
Please tell me about pyc magic number.

### ISSUE THREAD

**Issue by Bigdrea6** [MOCSCTF/CTF-Write-UP#1]
Reverse/TrendMicro2020-GateKeeper/
I had little knowledge and couldn't understand. I'm sorry. 
I would be happy if you could tell me.
The problem is about the magic number in this file (l11_opy_.pyc). The file command found that this file was python2.7. I also learned that the magic number of pyc differs depending on the version of python. However, I couldn't get any information that the magic number of this file would be "420d 0d0a 0000 0000 7079 6930". 
Please tell me why this value is reached.

**Comment by 920wY0u20wnCh11d** [comment]
Hi Bigdrea6,
when unpack the EXE file, there will come with several python library files(struct.pyc,pyiboot01_bootstrap.pyc,pyimod01_os_path.pyc..etc.) and that was successfully recognized by https://python-decompiler.com/. on my thought, l11_opy_.pyc should align the version with those library file. Hope this can help 👍

**Comment by Bigdrea6** [comment]
I understood. You think l11_opy_.pyc is the same as the Python version of the other files.
Thank you for your kindness!
